Регистрация:
<form action="/user/register" method="post">
    <div id="error"></div>
    Имя: <input type="text" name="name"> <br>
    Email: <input type="text" name="email"> <br>
    Пароль: <input type="password" name="password" placeholder="Введите пароль" required> <br>
    Подтвердите Пароль: <input type="password" name="password_r" placeholder="Подтвердите пароль" required> <br>
    <input type="submit" value="Зарегистрироваться">
</form>

<br>
<br>

Войти
<form action="/user/login" method="post">
    Имя: <input type="text" name="name"> <br>
    Пароль: <input type="password" name="password"> <br>
    <input type="submit" value="Войти">
</form>
<br>
<br>

{% if error %}
   <span style="color: red">{{error}}</span>
{% endif %}
